name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Run tests
      - name: Test
        run: dotnet test

      # Generate the website
      - name: Publish
        run: dotnet publish Blazor.Ionic.Demo/Blazor.Ionic.Demo.csproj --configuration Release

      # Edit the index.html file
      - name: Update index.html
        if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: <base href="/" />
          replace: <base href="/Blazor.Ionic/"/>
          include: index.html
          
      - name: Add 404 spa fix for github pages
        if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: Blazor.Ionic.Demo/bin/Release/netstandard2.1/publish/wwwroot/404.html
          FILE_BASE64: PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiPjx0aXRsZT5TaW5nbGUgUGFnZSBBcHBzIGZvciBHaXRIdWIgUGFnZXM8L3RpdGxlPjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij52YXIgcGF0aFNlZ21lbnRzVG9LZWVwPTE7dmFyIGw9d2luZG93LmxvY2F0aW9uO2wucmVwbGFjZShsLnByb3RvY29sKycvLycrbC5ob3N0bmFtZSsobC5wb3J0Pyc6JytsLnBvcnQ6JycpKyBsLnBhdGhuYW1lLnNwbGl0KCcvJykuc2xpY2UoMCwxK3BhdGhTZWdtZW50c1RvS2VlcCkuam9pbignLycpKycvPy8nKyBsLnBhdGhuYW1lLnNsaWNlKDEpLnNwbGl0KCcvJykuc2xpY2UocGF0aFNlZ21lbnRzVG9LZWVwKS5qb2luKCcvJykucmVwbGFjZSgvJi9nLCd+YW5kficpKyAobC5zZWFyY2g/JyYnK2wuc2VhcmNoLnNsaWNlKDEpLnJlcGxhY2UoLyYvZywnfmFuZH4nKTonJykrIGwuaGFzaCk7PC9zY3JpcHQ+IDwvaGVhZD48Ym9keT48L2JvZHk+PC9odG1sPg==
      # Publish the website
      - name: GitHub Pages action
        if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: Blazor.Ionic.Demo/bin/Release/netstandard2.1/publish/wwwroot
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
      - name: Publish NuGet
        if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: Blazor.Ionic/Blazor.Ionic.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: BlazorIonic
          INCLUDE_SYMBOLS: true
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
      - name: Publish Github Package Registry
        if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
        uses: Rebel028/publish-nuget@v2.6.3
        with:
          PROJECT_FILE_PATH: Blazor.Ionic/Blazor.Ionic.csproj
          NUGET_SOURCE: "https://nuget.pkg.github.com/Kukks"
          NUGET_KEY: ${{secrets.GH_TOKEN}}
          PACKAGE_NAME: BlazorIonic
          INCLUDE_SYMBOLS: false
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
